name: Deploy site

on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pnpm-version: [10]
        node-version: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare pnpm ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: ${{matrix.pnpm-version}}
      - name: Prepare Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Cache node_modules
        uses: actions/cache@v4
        env:
          cache-name: project-node-modules
        with:
          path: node_modules
          key: ${{runner.os}}-${{env.cache-name}}-${{hashFiles('package.json')}}
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm run generate
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy